version: '3'

services:
  fdfc_backend_service:
    image: fdfc_backend_image:latest
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: fdfc_backend_container
    volumes:
      - .:/fdfc_backend_volume
    ports:
      - "9999:8000"
