# Generated by Django 3.0.3 on 2020-08-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modifiedby', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('reference_number_1', models.CharField(max_length=255)),
                ('reference_number_2', models.CharField(max_length=255)),
                ('reference_number_3', models.CharField(max_length=255)),
                ('tracking_number_1', models.CharField(max_length=255)),
                ('tracking_number_2', models.CharField(max_length=255)),
                ('tracking_number_3', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'form_states',
            },
        ),
    ]
