# Generated by Django 3.0.3 on 2020-08-11 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_formstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstate',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='form_states', to='entities.User'),
            preserve_default=False,
        ),
    ]
