# Generated by Django 3.0.3 on 2020-08-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_formstate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
