# Generated by Django 3.0.3 on 2020-08-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstate',
            name='current_step',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
